// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503002540_BlueWavesMigrations")]
    partial class BlueWavesMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Achat", b =>
                {
                    b.Property<int>("IdAchat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAchat"));

                    b.Property<int>("CodeProduit")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCommande")
                        .HasColumnType("int");

                    b.Property<int>("NumeroStock")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdAchat");

                    b.HasIndex("CodeProduit");

                    b.HasIndex("NumeroCommande");

                    b.HasIndex("NumeroStock");

                    b.ToTable("ACHAT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Approvisionnement", b =>
                {
                    b.Property<int>("IdApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdApp"));

                    b.Property<string>("Certificat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CodeProduit")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReception")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroStock")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("RefFournisseur")
                        .HasColumnType("int");

                    b.HasKey("IdApp");

                    b.HasIndex("CodeProduit");

                    b.HasIndex("NumeroStock");

                    b.HasIndex("RefFournisseur");

                    b.ToTable("APPROVISIONNEMENT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Client", b =>
                {
                    b.Property<int>("RefClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RefClient"));

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PrenomClient")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("RefClient");

                    b.ToTable("CLIENT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Commande", b =>
                {
                    b.Property<int>("NumeroCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroCommande"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Delai")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("ExportNumeroExport")
                        .HasColumnType("int");

                    b.Property<int>("RefClient")
                        .HasColumnType("int");

                    b.HasKey("NumeroCommande");

                    b.HasIndex("ExportNumeroExport");

                    b.HasIndex("RefClient");

                    b.ToTable("COMMANDE", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export", b =>
                {
                    b.Property<int>("NumeroExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroExport"));

                    b.Property<int>("Delai")
                        .HasColumnType("int");

                    b.HasKey("NumeroExport");

                    b.ToTable("EXPORT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Fournisseur", b =>
                {
                    b.Property<int>("RefFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RefFournisseur"));

                    b.Property<string>("NomFournisseur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PrenomFournisseur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TelephoneFournisseur")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("RefFournisseur");

                    b.ToTable("FOURNISSEUR", (string)null);
                });

            modelBuilder.Entity("Core.Models.Produit", b =>
                {
                    b.Property<int>("CodeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodeProduit"));

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CodeProduit");

                    b.ToTable("PRODUIT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Stock", b =>
                {
                    b.Property<int>("NumeroStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroStock"));

                    b.Property<string>("NomStock")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("NumeroStock");

                    b.ToTable("STOCK", (string)null);
                });

            modelBuilder.Entity("Core.Models.StockProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeProduit")
                        .HasColumnType("int");

                    b.Property<int>("NumeroStock")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeProduit");

                    b.HasIndex("NumeroStock");

                    b.ToTable("STOCK_PRODUIT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Achat", b =>
                {
                    b.HasOne("Core.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("CodeProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Commande", "Commande")
                        .WithMany("Achats")
                        .HasForeignKey("NumeroCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("NumeroStock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Core.Models.Approvisionnement", b =>
                {
                    b.HasOne("Core.Models.Produit", "Produit")
                        .WithMany("Approvisionnements")
                        .HasForeignKey("CodeProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Stock", "Stock")
                        .WithMany("Approvisionnements")
                        .HasForeignKey("NumeroStock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Fournisseur", "Fournisseur")
                        .WithMany("Approvisionnement")
                        .HasForeignKey("RefFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Core.Models.Commande", b =>
                {
                    b.HasOne("Core.Models.Export", null)
                        .WithMany("Commande")
                        .HasForeignKey("ExportNumeroExport");

                    b.HasOne("Core.Models.Client", "Client")
                        .WithMany("Commande")
                        .HasForeignKey("RefClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Core.Models.StockProduit", b =>
                {
                    b.HasOne("Core.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("CodeProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("NumeroStock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Core.Models.Client", b =>
                {
                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Core.Models.Commande", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("Core.Models.Export", b =>
                {
                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Core.Models.Fournisseur", b =>
                {
                    b.Navigation("Approvisionnement");
                });

            modelBuilder.Entity("Core.Models.Produit", b =>
                {
                    b.Navigation("Approvisionnements");
                });

            modelBuilder.Entity("Core.Models.Stock", b =>
                {
                    b.Navigation("Approvisionnements");
                });
#pragma warning restore 612, 618
        }
    }
}
