// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Models.Achat", b =>
                {
                    b.Property<int>("IdAchat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodeProduit")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCommande")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdAchat");

                    b.HasIndex("CodeProduit");

                    b.HasIndex("NumeroCommande");

                    b.ToTable("ACHAT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Approvisionnement", b =>
                {
                    b.Property<int>("IdApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Certificat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CodeProduit")
                        .HasColumnType("int");

                    b.Property<int>("RefFournisseur")
                        .HasColumnType("int");

                    b.HasKey("IdApp");

                    b.HasIndex("CodeProduit");

                    b.HasIndex("RefFournisseur");

                    b.ToTable("APPROVISIONNEMENT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Client", b =>
                {
                    b.Property<int>("RefClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PrenomClient")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("RefClient");

                    b.ToTable("CLIENT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Commande", b =>
                {
                    b.Property<int>("NumeroCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodeExport")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("RefClient")
                        .HasColumnType("int");

                    b.HasKey("NumeroCommande");

                    b.HasIndex("CodeExport");

                    b.HasIndex("RefClient");

                    b.ToTable("COMMANDE", (string)null);
                });

            modelBuilder.Entity("Core.Models.Export", b =>
                {
                    b.Property<int>("NumeroExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Delai")
                        .HasColumnType("int");

                    b.HasKey("NumeroExport");

                    b.ToTable("EXPORT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Fournisseur", b =>
                {
                    b.Property<int>("RefFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomFournisseur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PrenomFournisseur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TelephoneFournisseur")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("RefFournisseur");

                    b.ToTable("FOURNISSEUR", (string)null);
                });

            modelBuilder.Entity("Core.Models.Produit", b =>
                {
                    b.Property<int>("CodeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_reception")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("NumeroStock")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CodeProduit");

                    b.HasIndex("NumeroStock");

                    b.ToTable("PRODUIT", (string)null);
                });

            modelBuilder.Entity("Core.Models.Stock", b =>
                {
                    b.Property<int>("NumeroStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("NumeroStock");

                    b.ToTable("STOCK", (string)null);
                });

            modelBuilder.Entity("Core.Models.Achat", b =>
                {
                    b.HasOne("Core.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("CodeProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("NumeroCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Core.Models.Approvisionnement", b =>
                {
                    b.HasOne("Core.Models.Produit", "Produit")
                        .WithMany("Approvisionnement")
                        .HasForeignKey("CodeProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Fournisseur", "Fournisseur")
                        .WithMany("Approvisionnement")
                        .HasForeignKey("RefFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Core.Models.Commande", b =>
                {
                    b.HasOne("Core.Models.Export", "Export")
                        .WithMany("Commande")
                        .HasForeignKey("CodeExport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Client", "Client")
                        .WithMany("Commande")
                        .HasForeignKey("RefClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Export");
                });

            modelBuilder.Entity("Core.Models.Produit", b =>
                {
                    b.HasOne("Core.Models.Stock", "Stock")
                        .WithMany("Produid")
                        .HasForeignKey("NumeroStock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Core.Models.Client", b =>
                {
                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Core.Models.Export", b =>
                {
                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Core.Models.Fournisseur", b =>
                {
                    b.Navigation("Approvisionnement");
                });

            modelBuilder.Entity("Core.Models.Produit", b =>
                {
                    b.Navigation("Approvisionnement");
                });

            modelBuilder.Entity("Core.Models.Stock", b =>
                {
                    b.Navigation("Produid");
                });
#pragma warning restore 612, 618
        }
    }
}
